// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6420.Attempt2.subsystems;


import org.usfirst.frc6420.Attempt2.RobotMap;
import org.usfirst.frc6420.Attempt2.commands.*;

import edu.wpi.first.wpilibj.ADXRS450_Gyro;
import edu.wpi.first.wpilibj.AnalogInput;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.command.PIDSubsystem;


/**
 *
 */
public class DriveBase extends PIDSubsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final SpeedController rightA = RobotMap.driveBaseRightA;
    private final SpeedController rightB = RobotMap.driveBaseRightB;
    private final SpeedController leftA = RobotMap.driveBaseLeftA;
    private final SpeedController leftB = RobotMap.driveBaseLeftB;
    private final RobotDrive driveBaseController = RobotMap.driveBaseDriveBaseController;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final ADXRS450_Gyro gyro = RobotMap.gyro;
    private final Encoder leftEncoder = RobotMap.leftDriveEncoder;
    private final Encoder rightEncoder = RobotMap.rightDriveEncoder;
    private double offset;
    private final AnalogInput us = RobotMap.ultrasonicSensor;
    private final int[] values = new int[5];
    private double movementPower = 0;
    private final double powerIncrement = 0.1;
    
    public DriveBase(){
    	super( 0.1, 0, 0 );
    	this.setSetpointRelative( 0.0 );
    }
    
    public void driveArcade( double movementValue, double turnValue ){
    	double diff = Math.abs( Math.abs( movementValue ) - Math.abs( movementPower ) );
    	if( diff < powerIncrement ){
    		movementPower = movementValue;
    	}else{
    		if( movementPower > movementValue ){
    			movementPower -= powerIncrement;
    		}else{
    			movementPower += powerIncrement;
    		}
    	}
    	if( Math.abs( turnValue ) < 0.1 ){
    		driveBaseController.arcadeDrive( movementPower, offset );
    	}else{
    		this.setSetpoint( offset );
    		driveBaseController.arcadeDrive( movementPower, turnValue );
    	}
    }
    
    public void driveArcadeAuto( double movementValue, double turnValue ){
    	movementPower = movementValue;
    	if( Math.abs( turnValue ) < 0.1 ){
    		driveBaseController.arcadeDrive( movementPower, offset );
    	}else{
    		this.setSetpoint( offset );
    		driveBaseController.arcadeDrive( movementPower, turnValue );
    	}
    }
    
    public void stop(){
    	movementPower = 0;
    	driveArcade( 0, 0 );
    }
 
    
    public double getAngle(){
    	return gyro.getAngle();
    }
    
    public double getAverageEncoderCount(){
    	return (rightEncoder.get() + leftEncoder.get()) * 0.5;
    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new DriveWithJoystick());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

	@Override
	protected double returnPIDInput() {
		// return the difference in encoder counts from right to left (left will be negative)
		return rightEncoder.get() - leftEncoder.get();
	}

	@Override
	protected void usePIDOutput(double output) {
		// TODO Auto-generated method stub
		offset = output;
	}
	
	public int getUltrasonicLevel(){
		int[] filter = new int[5];
		for( int i = 0; i < 4; i++ ){
			values[i+1] = values[i];
			filter[i+1] = values[i];
		}
		values[0] = us.getValue();
		filter[0] = values[0];
		//low pass
		int lowIndex = 0;
		for( int i = 1; i<5; i++ ){
			if( values[ lowIndex ] > values[ i ] ){
				lowIndex = i;
			}
		}
		values[ lowIndex ] = 0;
		int sum = 0;
		for( int i : values ) sum+= i;
		return sum / 4;
	}
}

