// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6420.Attempt2.commands;
import org.usfirst.frc6420.Attempt2.Robot;
import org.usfirst.frc6420.Attempt2.RobotMap;
import org.usfirst.frc6420.Attempt2.subsystems.DriveBase;

import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.interfaces.Gyro;

/**
 *
 */
public class AutoTurn extends Command {
	private int target;
	private double absolute_target;
	private Gyro gyro = RobotMap.gyro;
	private DriveBase driveBase = Robot.driveBase;

    public AutoTurn( int target ) {
		this.target = target;
	}

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

    // Called just before this Command runs the first time
    protected void initialize() {
    	this.absolute_target = gyro.getAngle() + target;
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	if( absolute_target - gyro.getAngle() < 0 ){
    		driveBase.driveArcade( 0, 0.6 );
    	}else{
    		driveBase.driveArcade( 0, -0.6 );
    	}
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
    	return Math.abs( gyro.getAngle() - this.absolute_target ) < 5;
    }

    // Called once after isFinished returns true
    protected void end() {
    	driveBase.driveArcade(0, 0);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
